name: Code Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: upload coverage to codacy
      run: |
        ls test/E13.Common.Core.Tests/TestResults/
    - name: upload coverage to codacy
      run: |
        export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/E13.Common.Core.Tests/TestResults/coverage.info --partial
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/E13.Common.Data.Db.Tests/TestResults/coverage.info --partial
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/E13.Common.Domain.Tests/TestResults/coverage.info --partial
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r test/E13.Common.Nunit.Tests/TestResults/coverage.info --partial
        bash <(curl -Ls https://coverage.codacy.com/get.sh) final

